{{ config(
    materialized='table',
    sort=['account_id']
) }}

select
    account_id,
    masterrecordid as master_record_id,
    name as account_name,
    type as account_type,
    parentid as parent_account_id,
    billingstreet as billing_street,
    billingcity as billing_city,
    billingstate as billing_state,
    billingpostalcode as billing_postal_code,
    billingcountry as billing_country,
    billinglatitude as billing_latitude,
    billinglongitude as billing_longitude,
    billinggeocodeaccuracy as billing_geocode_accuracy,
    shippingstreet as shipping_street,
    shippingcity as shipping_city,
    shippingstate as shipping_state,
    shippingpostalcode as shipping_postal_code,
    shippingcountry as shipping_country,
    shippinglatitude as shipping_latitude,
    shippinglongitude as shipping_longitude,
    shippinggeocodeaccuracy as shipping_geocode_accuracy,
    phone as account_phone,
    fax as account_fax,
    accountnumber as account_number,
    website as account_website,
    sic as sic_code,
    industry as account_industry,
    annualrevenue as annual_revenue,
    numberofemployees as number_of_employees,
    ownership as account_ownership,
    tickersymbol as ticker_symbol,
    description as account_description,
    rating as account_rating,
    site as account_site,
    ownerid as owner_id,
    createddate as created_date,
    createdbyid as created_by_id,
    lastmodifieddate as last_modified_date,
    lastmodifiedbyid as last_modified_by_id,
    systemmodstamp as system_mod_stamp,
    lastactivitydate as last_activity_date,
    jigsaw as jigsaw_id,
    jigsawcompanyid as jigsaw_company_id,
    cleanstatus as clean_status,
    accountsource as account_source,
    dunsnumber as duns_number,
    tradestyle as trade_style,
    naicscode as naics_code,
    naicsdesc as naics_description,
    yearstarted as year_started,
    sicdesc as sic_description,
    dandbcompanyid as dandb_company_id,
    operatinghoursid as operating_hours_id,
    customerpriority__c as customer_priority,
    sla__c as sla,
    active__c as is_active,
    numberoflocations__c as number_of_locations,
    upsellopportunity__c as upsell_opportunity,
    slaserialnumber__c as sla_serial_number,
    slaexpirationdate__c as sla_expiration_date
from {{ ref('stg_salesforce__account') }}
where isdeleted = false  -- Exclude deleted accounts
order by account_name
