{{ config(
    materialized='table',
    sort=['opportunity_id']
) }}

select
    opportunity_id,
    accountid as account_id,
    isprivate as is_private,
    name as opportunity_name,
    description as opportunity_description,
    stagename as stage_name,
    stagesortorder as stage_sort_order,
    amount as opportunity_amount,
    probability as opportunity_probability,
    expectedrevenue as expected_revenue,
    totalopportunityquantity as total_opportunity_quantity,
    closedate as close_date,
    type as opportunity_type,
    nextstep as next_step,
    leadsource as lead_source,
    isclosed as is_closed,
    iswon as is_won,
    forecastcategory as forecast_category,
    forecastcategoryname as forecast_category_name,
    campaignid as campaign_id,
    hasopportunitylineitem as has_opportunity_line_item,
    pricebook2id as pricebook_id,
    ownerid as owner_id,
    createddate as created_date,
    createdbyid as created_by_id,
    lastmodifieddate as last_modified_date,
    lastmodifiedbyid as last_modified_by_id,
    systemmodstamp as system_modstamp,
    lastactivitydate as last_activity_date,
    laststagechangedate as last_stage_change_date,
    fiscalyear as fiscal_year,
    fiscalquarter as fiscal_quarter,
    contactid as contact_id,
    primarypartneraccountid as primary_partner_account_id,
    contractid as contract_id,
    lastamountchangedhistoryid as last_amount_changed_history_id,
    lastclosedatechangedhistoryid as last_close_date_changed_history_id,
    deliveryinstallationstatus__c as delivery_installation_status,
    trackingnumber__c as tracking_number,
    ordernumber__c as order_number,
    currentgenerators__c as current_generators,
    maincompetitors__c as main_competitors,
    isdeleted as is_deleted,
from {{ ref('stg_salesforce__opportunity') }}
where isdeleted = false
order by opportunity_name
