version: 2

models:
  - name: fact_opportunity
    description: "Fact table containing sales opportunities data."
    columns:
      - name: opportunity_id
        description: "Primary key for the opportunity."
        tests:
          - unique
          - not_null